import wrapCustomElement from "@shoelace-style/react-wrapper";
export const ShoelaceButton = wrapCustomElement("sl-button");
export const ShoelaceAlert = wrapCustomElement("sl-alert");
export const ShoelaceIcon = wrapCustomElement("sl-icon");
export const ShoelaceInput = wrapCustomElement("sl-input");
export const ShoelaceTextarea = wrapCustomElement("sl-textarea");
export const ShoelaceButtonGroup = wrapCustomElement("sl-button-group");
export const ShoelaceTabPanel = wrapCustomElement("sl-tab-panel");
export const ShoelaceDialog = wrapCustomElement("sl-dialog");
export const ShoelaceForm = wrapCustomElement("sl-form");
export const ShoelaceSpinner = wrapCustomElement("sl-spinner");
export const ShoelaceAnimation = wrapCustomElement("sl-animation");
export const ShoelaceIconButton = wrapCustomElement("sl-icon-button");
export const ShoelaceTabGroup = wrapCustomElement("sl-tab-group");
export const ShoelaceTab = wrapCustomElement("sl-tab");
export const ShoelaceTooltip = wrapCustomElement("sl-tooltip");
export const ShoelaceBadge = wrapCustomElement("sl-badge");
export const ShoelaceDrawer = wrapCustomElement("sl-drawer");
