import wrapCustomElement from "@shoelace-style/react-wrapper";
export const ShoelaceButton = wrapCustomElement("sl-button");
export const ShoelaceAlert = wrapCustomElement("sl-alert");
export const ShoelaceIcon = wrapCustomElement("sl-icon");
export const ShoelaceInput = wrapCustomElement("sl-input");
export const ShoelaceTextarea = wrapCustomElement("sl-textarea");
export const ShoelaceButtonGroup = wrapCustomElement("sl-button-group");
export const ShoelaceTabPanel = wrapCustomElement("sl-tab-panel");
export const ShoelaceDialog = wrapCustomElement("sl-dialog");
export const ShoelaceForm = wrapCustomElement("sl-form");
export const ShoelaceSpinner = wrapCustomElement("sl-spinner");
